-- ==========================================
-- CRIAÇÃO DAS TABELAS
-- Projeto: Sistema de Reservas
-- ==========================================

create table usuarios (
  id bigint generated by default as identity primary key,
  nome varchar(100) not null,
  email varchar(100) not null unique,
  data_nascimento date not null,
  rua varchar(100),
  numero varchar(10),
  cidade varchar(50),
  estado char(2)
);

create table destinos (
  id bigint generated by default as identity primary key,
  nome varchar(100) not null,
  descricao text
);

create table reservas (
  id bigint generated by default as identity primary key,
  usuarios_id bigint not null,
  destinos_id bigint not null,
  data date not null,
  status varchar(20) not null,
  constraint fk_usuario
    foreign key (usuarios_id)
    references usuarios(id),
  constraint fk_destino
    foreign key (destinos_id)
    references destinos(id)
);